config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  root 'parts#index'
  resources :parts
  get 'tags/:tag', to: 'parts#index', as: "tag"
  get 'search', to: 'parts#search', s: "search"
  get 'all_tags', to: 'parts#all_tags', s: 'all_tags'
  get 'parts/:id/picture', to: 'parts#picture'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Disable registration
  devise_for :users, skip: [:registrations]
  as :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/part.rb
class Part < ApplicationRecord
  has_one_attached :picture
  has_many :taggings, dependent: :delete_all
  has_many :tags, through: :taggings
  validates :name, :picture, :item_number, presence: true
  paginates_per 10

  # This handles both creating the new tags and
  # mapping them to the Part through Tagging
  def all_tags=(name)
    self.tags = name.strip.split(",").map do |name|
      if name != " "
        Tag.where(name: name.strip.downcase).first_or_create!
      end
    end
  end

  # Gets all of the tags under a part and converts all
  # of the names to a comma delimited string.
  # This is mainly for use in views
  def all_tags
    self.tags.map(&:name).join(", ")
  end

  # 
  def self.tagged_with(name)
    if Tag.find_by_name(name) != nil
      Tag.find_by_name(name).parts
    else
      return []
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :parts, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :part
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:picture]
  protect_from_forgery unless: -> { request.format.json? }

  # GET /parts or /parts.json
  def index
    @parts = []
    # Handles GET requests off of tags/<tag> to just utilize the parts index,
    # rather than rendering a different view just for that.
    if params[:tag]
      @parts = Part.tagged_with(params[:tag])
    # Fetches the 10 most linked/viewed pictures
    else
      parts = Part.all
      parts = parts.order('views')
      @parts = parts.reverse
    end

    @parts = Kaminari.paginate_array(@parts).page(params[:page]).per(10)
  end

  # GET /parts/1 or /parts/1.json
  def show
    if @part.views == nil
      @part.views = 0
    end
    @part.views += 1
    @part.save
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts or /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: "Part was successfully created." }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1 or /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: "Part was successfully updated." }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1 or /parts/1.json
  # Every time a part is deleted, it'll prune the database of
  # any tags that have no parts associated
  def destroy
    @part.destroy
    Tag.all.each do |tag|
      if tag.parts.length == 0
        tag.destroy
      end
    end
    respond_to do |format|
      format.html { redirect_to parts_url, notice: "Part was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  # GET /search/query=<query>&commit=Search
  # Utilizes the tagged_with method off of Parts to get every Part with the supplied tag
  # it then trims the list by making sure all searched tags are present on the item
  # Then prunes the list of any duplicates
  # It returns the search.js.erb after for client side rendering
  def search
    @query = params[:query].downcase
    @parts = []
    if @query != nil
      tags = @query.split(",").map
      tags.each do |tag|
        @parts += Part.tagged_with(tag.strip)
      end
    else
      @parts = Part.all
    end
    
    # exclusive searching
    # tags.each do |tag|
    #   @parts.delete_if { |part| !part.all_tags.include? tag.strip }
    # end


    @parts = @parts.uniq
    # sorts the results by the number of matching tags,
    # see num_tags at the bottom for more info
    @parts = @parts.sort_by {|part| num_tags(part, tags)}
    

    
    @parts = Kaminari.paginate_array(@parts).page(params[:page]).per(10)
    respond_to do |format|
      format.js
    end
  end

  def all_tags
    @tags = Tag.all

    respond_to do |format|
      format.js
    end
  end

  def picture
    @part = Part.find(params[:id])
    if @part != nil
      redirect_to url_for(@part.picture)
    else
      redirect_to 'index'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def part_params
      params.require(:part).permit(:name, :picture, :item_number, :all_tags, :price, :notes, :link1, :link2, :link3, :link1_title, :link2_title, :link3_title)
    end

    # sort_by orders smallest to largest
    # so we count negatively, the one with
    # the lowest number is ordered to the top
    # and the highest is ordered to the bottom
    # calling reverse after is another step, so
    # just doing it here instead skips that
    def num_tags(part, tags)
      count = 0
      tags.each do |tag|
        if part.all_tags.include? tag
          count -= 1
        end
      end
      return count
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parts_helper.rb
module PartsHelper
  def tag_links(tags)
    tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PartsDatabase</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Tailwind CSS -->
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  </head>

  <body style="margin: 0">
    <%= render 'parts/header' %>
    <div id="notice" class="notice"><h3><%= notice %></h3></div>
    <% if alert %>
      <div class="alert alert-danger notice"><h3><%= alert %></h3></div>
    <% end %>
    <%= yield %>
  </body>
  <script>
  $(document).ready(function(){
    if ($("#notice").children().length >= 1){
      $("#notice").delay(1000).fadeOut(1000);
    }
  })

  </script>
</html>

app/views/parts/_all_tags.html.erb
<h1>Tags:</h1>
<hr>
<% if @tags != nil %>
    <div class="p-3 text-base text-xl">
        <% @tags.each do |tag| %>
            <%= raw tag_links(tag.name) %>,
        <% end %>
    </div>
<% else %>
    No Tags Found
<% end %>

app/views/parts/_cart.html.erb
<div id="cart" class="collapsed cart" style="display: none">
  <div class="w-full bg-gradient-to-r from-blue-600 to-blue-200 absolute top-0 rounded-top-lg">
    <%= image_tag('close.png', onClick: "hideCart()", class: 'h-5 block float-right mb-3 mr-1 mt-1') %>.
  </div>
  <div class="relative">
    <div class="overflow-auto mt-8" style="height:500px;">
      <table class="collapsed">
        <thead>
          <tr>
            <th>Name</th>
            <th>Item Code</th>
            <th>Price</th>
            <th></th>
          </tr>
        </thead>
        <tbody id="cart-items">
        </tbody>
      </table>
    </div>
  </div>
  <hr>
  <div class="absolute bottom-0 right-0">
    <div id="total" class="w-full"></div>
    <div class="text-red-600 w-full" onClick="emptyCart()">Clear Cart</div>
  </div>
</div>

<script>
function addToCart(item_id, item_number, item_price, item_name){
  var part = {
      itemName: item_name,
      itemNum: item_number,
      price: item_price
  }
  localStorage.setItem(item_id, JSON.stringify(part))
  $('#notice').html("<h3> Added to Cart </h3>")
  $('#notice').fadeIn(500).delay(1000).fadeOut(500)
}
    
    
function cartToggle(){
const cartStatus = document.getElementById("cart")
    if (cartStatus.classList.contains('collapsed')) {
        showCart()
    } else {
        hideCart()
    }
}
    
function cartItemTemplate(item_number, price, id, name){
  if (price == "") {
    price = 0.0
  }
  return"<tr id='"+id+"'><td class='itemnum select-all'>"+name+"</td><td class='itemnum select-all'>"+item_number+"</td><td class='price'>$"+price+"</td><td class='text-red-400' onclick='removeFromCart("+id+")'>Remove</td></tr>"
}

function calculateTotal(){
  var cart = localStorage
  var total = 0.0
  for (const [item_id, part_object] of Object.entries(cart)) {
    part = JSON.parse(part_object)
    if (part.price != ""){
      total += parseInt(part.price)
    }
  }
  document.getElementById("total").innerHTML = "Total: $"+total
}
    
function showCart(){
  var cart = localStorage
  var content = ""
  var total = 0.0
  for (const [item_id, part_object] of Object.entries(cart)) {
    part = JSON.parse(part_object)
    content += cartItemTemplate(part.itemNum, part.price, item_id, part.itemName)
    if (part.price != ""){
      total += parseInt(part.price)
    }
  }

  document.getElementById("total").innerHTML = "Total: $"+total

  document.getElementById("cart").classList.remove("collapsed")

  const cartItems = document.getElementById("cart-items")
  cartItems.innerHTML = content

  $('#cart').fadeIn(500)
}

function hideCart(){
  $('#cart').fadeOut(500)
  document.getElementById("cart").classList.add("collapsed")
  const cartItems = document.getElementById("cart-items")
  cartItems.innerHTML = ""
  document.getElementById("total").innerHTML = ""
}

function emptyCart(){
  const cartItems = document.getElementById("cart-items")
  cartItems.innerHTML = "<h3>Cleared</h3>"
  localStorage.clear()
  document.getElementById("cart").classList.add("collapsed")
  document.getElementById("total").innerHTML = "Total: $0"


  $('#cart').delay(500).fadeOut(500)
}
    
function removeFromCart(part_id){
  localStorage.removeItem(part_id)
  const cartItems = document.getElementById("cart-items")
  $('#' + part_id).fadeOut(500)
  calculateTotal()
}
</script>

app/views/parts/_form.html.erb
<div class="container">
  <%= form_with(model: part, remote: true) do |form| %>
    <% if part.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

        <ul>
          <% part.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div class="flex-wrap">
    <div class="field">
      <%= form.label 'Name:' %>
      <%= form.text_field :name, placeholder: :name, class: 'text-field' %>
    </div>

    <div class="field">
      <%= form.label 'Item Number:' %>
      <%= form.text_field :item_number, placeholder: :item_number, class: 'text-field' %>
    </div>

    <div class="field">
      <%= form.label 'Picture:' %>
      <label class="button" tabindex="0">
        <%= form.file_field :picture, class: 'upload-button', onchange: "preview()" %>
        Upload Photo
      </label>
      <img id="frame" class="hidden" src="" width="100px" height="100px"/>
    </div>
  </div>

  <div class="flex">
    <div>
      <span class="field">
        <%= form.label 'Notes:' %>
        <%= form.text_area :notes, placeholder: :notes, class: 'text-field' %>
      </span>

      <span class="field">
        <%= form.label 'Price:' %>
        <%= form.number_field :price, value: @part.price ? '%.2f' % @part.price : nil, min: 0, step: 0.01, class: 'text-field' %>
      </span>
    </div>
  </div>

  <div class="flex">Links to purchase part online:</div>
  <div class="flex-wrap">
    <div class="flex-wrap">
      <span class="field">
        <%= form.text_field :link1, placeholder: :link1, class: 'text-field' %>
      </span>
      <span class="field">
        <%= form.text_field :link1_title, placeholder: :link1_title, class: 'text-field' %>
      </span>
    </div>

    <div class="flex-wrap">
      <span class="field">
        <%= form.text_field :link2, placeholder: :link2, class: 'text-field' %>
      </span>
      <span class="field">
        <%= form.text_field :link2_title, placeholder: :link2_title, class: 'text-field' %>
      </span>
    </div>

    <div class="flex-wrap">
      <span class="field">
        <%= form.text_field :link3, placeholder: :link3_title, class: 'text-field' %>
      </span>
      <span class="field">
        <%= form.text_field :link3_title, placeholder: :link3_title, class: 'text-field' %>
      </span>
    </div>

  </div>

  <div class="flex">
    <div class="large-10 large-centered columns">
        <%= form.label 'Tags:' %>
        <%= form.text_field :all_tags, placeholder: :all_tags || "Tags separated with comma" , class: 'text-field' %>
      </div>
  </div>

    <% if action_name == 'new' %>
      <div class="actions">
        <%= form.submit "Create Part", class: 'button' %>
      </div>
    <% else %>
      <div class="actions">
        <%= form.submit "Update Part", class: 'button' %>
      </div>
    <% end %>
  <% end %>
</div>

<script>
// from: https://stackoverflow.com/a/62167551
function preview() {
  $('#frame').removeClass('hidden')
    frame.src=URL.createObjectURL(event.target.files[0]);
}
</script>

app/views/parts/_header.html.erb
<div class="header">
    <div class="header-wrap">
      <h1 class="text-white inline ml-3"><a href="/">Parts Database</a></h1>
      <% if user_signed_in? %>
        <span class="nav-menu-button bg-green-400 hover:bg-green-500 inline md:hidden rounded-l-full md:rounded-none" onClick="toggleMenu()">Menu ☰</span>
        <%= link_to '/all_tags', remote: true do %>
          <span class="nav-menu-button bg-green-400 hover:bg-green-500 hidden md:inline">All Tags</span>
        <% end %>
        <span class="nav-menu-button bg-yellow-400 hover:bg-yellow-500 rounded-l-full hidden md:rounded-none md:inline" onClick="cartToggle()">Cart</span>
        <%= link_to 'Add Part', new_part_path, method: :get, class: "nav-menu-button bg-red-400 hover:bg-red-500 rounded-l-full hidden md:inline" %>
      <% end %>


    </div>
    <div id="menu-items" class="menu-window hidden bg-gray-50">
      <%= link_to new_part_path do %>
        <div  class="nav-menu-item bg-red-400 hover:bg-red-500 w-full md:hidden" onClick="toggleMenu()">
          Add Part
        </div>
      <% end %>
      <%= link_to "/all_tags", remote: true do %>
        <div  class="nav-menu-item bg-green-400 hover:bg-green-500 w-full" onClick="toggleMenu()">
          All Tags
        </div>
      <% end %>
    </div>
  

  <% if user_signed_in? %>
    <%= render 'parts/search_form' %> 
  <% end %>
</div>

<% if user_signed_in? %>
  <%= render 'cart' %>
<% end %>

<script>

  $(document).ready(function() {
      $("all").click(function() {
          $("all").submit();
      });

      // hide away the search bar when scrolling
      // Reimplementation of previous method to prevent
      // the animation from playing in a loop, bouncing the content
      // This just sets the trigger distance from the top to a wide enough
      // value that the header expanding and contracting doesnt re-trigger the event
      $(window).on('scroll' , function(){
        var scroll = $(window).scrollTop();
        if(scroll > 500){
          $('#search-bar').slideUp(250)
        }
        if (scroll < 200){
          $('#search-bar').slideDown(250)
        }
      });
  });

  function toggleMenu(){
    if ($("#menu-items").is(":visible")){
      $("#menu-items").slideUp(500)
    } else {
      $("#menu-items").slideDown(500)
    }
    
  }

  // Handles sliding the search bar up and down while using the site
  // This is primarily to give more screen real estate when on mobile
  // Primary functions from here: https://stackoverflow.com/a/34996740
  // Modified to just slide in and out, rather than modify the CSS of it
  

  $(document).ready(function(){
   
});
</script>

app/views/parts/_search.html.erb
<h1>Parts:</h1>
<hr>
<% if @parts != [] %>
  <div class="results_container">
    <% @parts.each do |part| %>
      <div class="result-card">
        <div class="result-name"><%= part.name %></div>
        <div class="result-content">
          <b>Item Number:</b>
          <p class="truncate"><%= part.item_number %></p>

          <div class="result-name-container">
            <a href="<%= url_for(part) %>">
            <% if part.picture.representable? %>
              <% if part.picture.previewable? %>
               <%= image_tag part.picture.preview(resize_to_limit: [200, 200]), class: 'result-image' %>
              <% else %>
                <%= image_tag part.picture.representation(resize_to_limit: [200, 200]), class: 'result-image' %>
              <% end %>
            <% else %>
              <%= image_tag 'not-representable.png', class: 'result-image' %>
            <% end %>
            </a>
          </div>
          <b>Notes:</b>
          <div class="result-tags overflow-auto">
            <%= sanitize part.notes %>
          </div>
        </div>

          <div class="add-to-cart hidden md:block" onClick="addToCart('<%= part.id %>', '<%= part.item_number %>', '<%= part.price %>', '<%= part.name %>')">
            Add to Cart
          </div>

        <a href="<%= part_path(part) %>">
          <div class="card-actions">
            Show 
          </div>
        </a>
      </div>
    <% end %>
  </div>
  
  <div class="pagination">
    <% if action_name == 'search' or action_name == 'all' or action_name == 'tags' %>
      <%= paginate @parts, remote: true, window: 2 %>
    <% else %>
      <%= paginate @parts, window: 2 %>
    <% end %>
  </div>
<% else %>
  <br>
  <p><strong>No Results</strong></p>
<% end %>

app/views/parts/_search_form.html.erb
<div id="search-bar" class="search-bar flex-wrap static">
  <%= form_with url: "/search", id: 'search', local: false, class: "", method: :get do |form| %>
    <%= form.text_field :query, class: "search-field", placeholder: "Enter tags separated by commas" %>
    <%= form.submit "Search", class: "search-button" %>
  <% end %>

</div>


<script>
  $(document).ready(function() {
      $("query").click(function() {
          $("query").submit();
      });
  });
</script>

app/views/parts/all.js.erb
$('#results').html("<%= j render(partial: 'search') %>")

app/views/parts/all_tags.js.erb
$('#results').html("<%= j render(partial: 'all_tags') %>")

app/views/parts/edit.html.erb
<div id="results" class="p-3">
    <h1>Editing Part</h1>

    <%= render 'form', part: @part %>
</div>

app/views/parts/index.html.erb
<div class="p-3">
  <div id="results">
    <%= render 'search' %>
  </div>
</div>

app/views/parts/new.html.erb
<div id="results" class="p-3">
    <h1>New Part</h1>

    <%= render 'form', part: @part %>
</div>

app/views/parts/search.js.erb
$('#results').html("<%= j render(partial: 'search') %>")

app/views/parts/show.html.erb
<div id="results" class="p-3">
  <div id="image-copied-notice" class="notice" style="display: none">
      <h1>Copied!</h1>
  </div>

  <h1><%= @part.name %></h1>
  <hr>

  <div class="flex flex-wrap md:flex-nowrap bg-gray-50">
    <div class="show-info-container w-full md:w-1/4 overflow-hidden mr-1 border-r bg-white">

      <p class="text-lg">Item Number:</p>
      <p class="text-lg pl-3 select-all"><%= @part.item_number %></p>

      <p class="text-lg">Price:</p>
      <p class="text-lg pl-3"><%= number_to_currency(@part.price) %></p>
      
      <p class="text-lg">Notes:</p>
      <div class="notes-content" >

        <%= sanitize @part.notes %>

      </div>
      
      <p class="text-lg">External Links:</p>
      <div class="text-base pl-3">
      
      <% [{link: @part.link1, title: @part.link1_title}, {link: @part.link2, title: @part.link2_title}, 
        {link: @part.link3, title: @part.link3_title}].each do |part| %>
        <% if part != '' %>
          <%= link_to part[:title], part[:link], target: "_blank" %></br>
        <% end %>
      <% end %>
      </div>

      <p class="text-lg">Tags:</p>
      <div class="h-40 border rounded-md p-3 mr-2">
        <p class="text-base"><%= raw tag_links(@part.all_tags) %></p>
      </div>

      <p class="hidden md:inline">Last Updated: <%= @part.updated_at %></p>
      <!-- Actions -->
      <div class="show-actions justify-center">
        <%= link_to 'Edit', edit_part_path(@part), class: "show-action bg-green-400 hover:bg-green-500 rounded-bl-lg", method: :get %>
        <%= link_to 'Delete', @part, class: "show-action bg-red-400 hover:bg-red-500 rounded-br-lg", method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>

    </div>

    <div class="w-2/3 overflow-auto flex-initial">
      <div class="w-11/12 overflow">
      <% if @part.picture.representable? %>
        <% if @part.picture.previewable? %>
          <img id="picture-container" class="block" src="<%= url_for(@part.picture.preview(resize: '400x600')) %>">
          <p class="button hidden md:inline-flex" id="click-action-desc" onClick="toggleDoc()">Show PDF</p>
          <p class="button inline-flex" onclick="copyImageLink()">Copy Link</p>

          <div id="document-container" style="display:none">
            <embed src=<%= url_for(@part.picture) %> width="100%" height="600" style="border: none; display: hidden;" > </embed>
          </div>
        <% else %>
          <p>(click to copy URL to clipboard)</p>
          <img onClick="copyImageLink()" class="block" src="<%= url_for(@part.picture) %>">
        <% end %>
      <% else %>
        <%= image_tag 'not-representable.png', class: 'result-image' %>
        <hr>
        <a href="<%= url_for(@part.picture) %>" class="button hidden md:inline-flex">Download</a>
      <% end %>
      </div>
    </div>
    
  </div>
  <script>
  function copyImageLink() {
    console.log("Copied image to clipboard")
    
    navigator.clipboard.writeText("<%= root_url + url_for(@part) + '/picture' %>")
    $('#image-copied-notice').fadeIn(500)
    $('#image-copied-notice').delay(3000).fadeOut(1000)
  }

  function toggleDoc() {
    if ( $('#document-container').css('display') != 'none'){
      $('#document-container').css("display","none").html("<embed src=<%= url_for(@part.picture) %> width='100%' height='600' style='border: none; display: hidden;' > </embed>");
      $('#picture-container').css("display","");
      $('#click-action-desc').text("Show PDF");
    } else {
      $('#document-container').css("display","");
      $('#picture-container').css("display","none");
      $('#click-action-desc').text("Preview");
    }
  }
  </script>
</div>